Repository oixel/DoneTogether, pull requests merged in 2025-04, with the labels that each got.

#56 Enhance goal management and user interface improvements
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api.ts
  client/src/api/goalRequests.ts
  client/src/api/userRequests.ts
  client/src/assets/icons/inboxdoodle.svg
  client/src/components/AddUser.tsx
  client/src/components/EditGoalPopUp.tsx
  client/src/components/EditPopUp.tsx
  client/src/components/Goal.tsx
  client/src/components/GoalList.tsx
  client/src/components/GoalPopUp.tsx
  client/src/components/User.tsx
  client/src/pages/AboutUs.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Dashboard/Dashboard.css
  client/src/pages/Dashboard/Dashboard.tsx
  client/src/pages/LandingPage.tsx
  client/src/pages/LandingPage/LandingPage.tsx
  client/src/pages/NotFound.tsx
  client/src/styles/AboutUs.css
  client/src/styles/Dashboard.css
  client/src/styles/GoalList.css
  client/src/styles/LandingPage.css
  client/src/styles/NotFound.css
  client/src/styles/User.css
  client/src/styles/addUser.css
  client/src/styles/globalStyles.css
  client/src/types/goalData.ts
  client/src/types/userData.ts
  package-lock.json
  package.json
  server/api/goalRequests.cjs
  server/api/userRequests.js
  server/server.js
Labels: enhancement, backend

#68 Add feature that resets the completion statuses on goals every day
  client/src/api/goalRequests.ts
  client/src/components/EditPopUp.tsx
  client/src/components/Goal.tsx
  client/src/components/GoalPopUp.tsx
  client/src/styles/popUp.css
  client/src/types/goalData.ts
  package-lock.json
  package.json
  server/api/completionReset.js
  server/api/goalRequests.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: frontend, backend

#75 Implement user streak tracking and display features across components
  client/src/components/Goal.tsx
  client/src/components/User.tsx
  client/src/pages/Dashboard.tsx
  client/src/styles/Goal.css
  client/src/styles/User.css
  client/src/types/userData.ts
  server/api/completionReset.js
  server/api/goalRequests.js
  server/config/serverInfo.json
Labels: enhancement
